// ============================================================
//  features.h  —  Real-time Feature Extraction for ESP32
//  Fall Detection System | MPU6050 / SisFall Pipeline
// ============================================================
//
//  CRITICAL: Every formula here mirrors the Python function
//  extract_features_from_window() exactly.
//  Changing ANY formula will break compatibility with fall_model.h.
//
//  Feature order (46 total) — must match Features struct in fall_model.h:
//
//  [Per-axis × 6 axes × 6 stats = 36]
//    acc_x : mean, std, min, max, rms, range
//    acc_y : mean, std, min, max, rms, range
//    acc_z : mean, std, min, max, rms, range
//    gyro_x: mean, std, min, max, rms, range
//    gyro_y: mean, std, min, max, rms, range
//    gyro_z: mean, std, min, max, rms, range
//
//  [SVM accelerometer × 2 = 2]
//    svm_acc_mean, svm_acc_max
//
//  [SVM gyroscope × 2 = 2]
//    svm_gyro_mean, svm_gyro_max
//
//  [Jerk accelerometer only × 3 axes × 2 stats = 6]
//    acc_x_jerk_mean, acc_x_jerk_var
//    acc_y_jerk_mean, acc_y_jerk_var
//    acc_z_jerk_mean, acc_z_jerk_var
//
//  Total: 36 + 2 + 2 + 6 = 46 features
// ============================================================

#pragma once
#include <math.h>    // sqrtf(), fabsf()
#include <stdint.h>

// ── Window size — must match Python WINDOW_SIZE = 100 ──────────────────────
#define WINDOW_SIZE 100

// ── Jerk array length = WINDOW_SIZE - 1 = 99 ───────────────────────────────
// Python: np.diff(window[:, i]) produces an array of length N-1
#define JERK_SIZE   (WINDOW_SIZE - 1)

// ============================================================
//  Features struct
//  Field names MUST exactly match the sanitised names in
//  fall_model.h (generated by the Python C-export function).
//  Order here = order in which rf tree nodes reference fields.
// ============================================================
typedef struct {
    // ── Accelerometer X ──────────────────────────────────────
    float acc_x_mean;
    float acc_x_std;
    float acc_x_min;
    float acc_x_max;
    float acc_x_rms;
    float acc_x_range;

    // ── Accelerometer Y ──────────────────────────────────────
    float acc_y_mean;
    float acc_y_std;
    float acc_y_min;
    float acc_y_max;
    float acc_y_rms;
    float acc_y_range;

    // ── Accelerometer Z ──────────────────────────────────────
    float acc_z_mean;
    float acc_z_std;
    float acc_z_min;
    float acc_z_max;
    float acc_z_rms;
    float acc_z_range;

    // ── Gyroscope X ──────────────────────────────────────────
    float gyro_x_mean;
    float gyro_x_std;
    float gyro_x_min;
    float gyro_x_max;
    float gyro_x_rms;
    float gyro_x_range;

    // ── Gyroscope Y ──────────────────────────────────────────
    float gyro_y_mean;
    float gyro_y_std;
    float gyro_y_min;
    float gyro_y_max;
    float gyro_y_rms;
    float gyro_y_range;

    // ── Gyroscope Z ──────────────────────────────────────────
    float gyro_z_mean;
    float gyro_z_std;
    float gyro_z_min;
    float gyro_z_max;
    float gyro_z_rms;
    float gyro_z_range;

    // ── SVM Accelerometer ─────────────────────────────────────
    float svm_acc_mean;
    float svm_acc_max;

    // ── SVM Gyroscope ─────────────────────────────────────────
    float svm_gyro_mean;
    float svm_gyro_max;

    // ── Jerk — Accelerometer only ─────────────────────────────
    // Python: jerk = np.abs(np.diff(window[:, i]))
    float acc_x_jerk_mean;
    float acc_x_jerk_var;
    float acc_y_jerk_mean;
    float acc_y_jerk_var;
    float acc_z_jerk_mean;
    float acc_z_jerk_var;

} Features;


// ============================================================
//  SECTION A — Scalar helper functions
//  All operate on a const float array of length n.
//  All use float arithmetic only (no double).
// ============================================================

// ── Mean ────────────────────────────────────────────────────
// Python: np.mean(col)
static inline float feat_mean(const float *x, int n)
{
    float sum = 0.0f;
    for (int i = 0; i < n; i++) sum += x[i];
    return sum / (float)n;
}

// ── Population variance ─────────────────────────────────────
// Python: np.var(col)  ← population variance (ddof=0 by default)
// Formula: mean( (x - mean)^2 )
static inline float feat_var(const float *x, int n, float mean)
{
    float sum = 0.0f;
    for (int i = 0; i < n; i++) {
        float d = x[i] - mean;
        sum += d * d;
    }
    return sum / (float)n;
}

// ── Population standard deviation ───────────────────────────
// Python: np.std(col)  ← population std (ddof=0 by default)
// Formula: sqrt( var )
static inline float feat_std(const float *x, int n, float mean)
{
    return sqrtf(feat_var(x, n, mean));
}

// ── Minimum ─────────────────────────────────────────────────
// Python: np.min(col)
static inline float feat_min(const float *x, int n)
{
    float m = x[0];
    for (int i = 1; i < n; i++) if (x[i] < m) m = x[i];
    return m;
}

// ── Maximum ─────────────────────────────────────────────────
// Python: np.max(col)
static inline float feat_max(const float *x, int n)
{
    float m = x[0];
    for (int i = 1; i < n; i++) if (x[i] > m) m = x[i];
    return m;
}

// ── Root Mean Square ────────────────────────────────────────
// Python: np.sqrt(np.mean(col ** 2))
static inline float feat_rms(const float *x, int n)
{
    float sum = 0.0f;
    for (int i = 0; i < n; i++) sum += x[i] * x[i];
    return sqrtf(sum / (float)n);
}

// ── Range ───────────────────────────────────────────────────
// Python: np.max(col) - np.min(col)
// Note: we pass pre-computed min/max to avoid a second full scan
static inline float feat_range(float col_min, float col_max)
{
    return col_max - col_min;
}


// ============================================================
//  SECTION B — Jerk helpers
//
//  Python:
//    jerk = np.abs(np.diff(window[:, i]))   → length 99
//    feats[f"{ax}_jerk_mean"] = np.mean(jerk)
//    feats[f"{ax}_jerk_var"]  = np.var(jerk)   ← population var
//
//  We compute both mean and variance in a single pass using
//  the two-pass compensated method to match numpy's ddof=0.
// ============================================================

// Fills *jerk_mean and *jerk_var for one axis array x of length WINDOW_SIZE.
// Uses a stack-allocated jerk buffer of size JERK_SIZE (99 floats = 396 bytes).
static inline void feat_jerk(const float *x,
                              float *jerk_mean,
                              float *jerk_var)
{
    // Stack buffer — 99 floats, safe for ESP32 (396 bytes)
    float jerk[JERK_SIZE];

    // Step 1: compute |x[i+1] - x[i]| for i in 0..98
    // Python: np.abs(np.diff(window[:, i]))
    for (int i = 0; i < JERK_SIZE; i++) {
        jerk[i] = fabsf(x[i + 1] - x[i]);
    }

    // Step 2: mean of jerk — Python: np.mean(jerk)
    float sum = 0.0f;
    for (int i = 0; i < JERK_SIZE; i++) sum += jerk[i];
    float mean = sum / (float)JERK_SIZE;
    *jerk_mean = mean;

    // Step 3: population variance — Python: np.var(jerk)  [ddof=0]
    float var_sum = 0.0f;
    for (int i = 0; i < JERK_SIZE; i++) {
        float d = jerk[i] - mean;
        var_sum += d * d;
    }
    *jerk_var = var_sum / (float)JERK_SIZE;
}


// ============================================================
//  SECTION C — Per-axis feature block
//
//  Computes all 6 per-axis features for one axis array in a
//  single pass through the data (min/max/sum/sum-of-squares),
//  then derives mean, std, rms, range from those accumulators.
//  This avoids redundant loops for the same axis.
// ============================================================
typedef struct {
    float mean;
    float std;
    float col_min;
    float col_max;
    float rms;
    float range;
} AxisFeats;

static inline AxisFeats compute_axis(const float *x, int n)
{
    // Single-pass accumulators
    float sum    = 0.0f;   // for mean
    float sum_sq = 0.0f;   // for rms
    float mn     = x[0];   // running min
    float mx     = x[0];   // running max

    for (int i = 0; i < n; i++) {
        sum    += x[i];
        sum_sq += x[i] * x[i];
        if (x[i] < mn) mn = x[i];
        if (x[i] > mx) mx = x[i];
    }

    float mean = sum / (float)n;
    float rms  = sqrtf(sum_sq / (float)n);

    // Population std — second pass (two-pass is numerically stable)
    // Python: np.std(col) uses ddof=0
    float var_sum = 0.0f;
    for (int i = 0; i < n; i++) {
        float d = x[i] - mean;
        var_sum += d * d;
    }
    float std = sqrtf(var_sum / (float)n);

    AxisFeats af;
    af.mean    = mean;
    af.std     = std;
    af.col_min = mn;
    af.col_max = mx;
    af.rms     = rms;
    af.range   = mx - mn;
    return af;
}


// ============================================================
//  SECTION D — SVM helpers
//
//  Python:
//    svm_acc  = np.sqrt(window[:,0]**2 + window[:,1]**2 + window[:,2]**2)
//    feats["svm_acc_mean"] = np.mean(svm_acc)
//    feats["svm_acc_max"]  = np.max(svm_acc)
// ============================================================

// Computes mean and max of sqrt(a^2 + b^2 + c^2) over WINDOW_SIZE samples.
// a/b/c are three parallel axis arrays (e.g. acc_x, acc_y, acc_z).
static inline void feat_svm(const float *a, const float *b, const float *c,
                             int n,
                             float *svm_mean, float *svm_max)
{
    float sum = 0.0f;
    float mx  = 0.0f;

    for (int i = 0; i < n; i++) {
        float sv = sqrtf(a[i]*a[i] + b[i]*b[i] + c[i]*c[i]);
        sum += sv;
        if (sv > mx) mx = sv;
    }

    *svm_mean = sum / (float)n;
    *svm_max  = mx;
}


// ============================================================
//  MAIN FUNCTION: compute_features()
//
//  Call this once per completed 100-sample window.
//
//  Parameters
//  ----------
//  ax, ay, az : float arrays of length WINDOW_SIZE — accelerometer (g)
//  gx, gy, gz : float arrays of length WINDOW_SIZE — gyroscope (rad/s)
//  f          : pointer to Features struct to fill
//
//  The caller is responsible for providing aligned, complete
//  100-sample arrays before calling this function.
// ============================================================
static inline void compute_features(
    const float *ax, const float *ay, const float *az,
    const float *gx, const float *gy, const float *gz,
    Features    *f)
{
    // ── Per-axis blocks ───────────────────────────────────────────────────
    //
    // Python iterates axes = ["acc_x","acc_y","acc_z","gyro_x","gyro_y","gyro_z"]
    // and computes mean/std/min/max/rms/range in that order for each axis.
    // We preserve exactly that field order in the struct.

    AxisFeats af;

    // acc_x
    af = compute_axis(ax, WINDOW_SIZE);
    f->acc_x_mean  = af.mean;
    f->acc_x_std   = af.std;
    f->acc_x_min   = af.col_min;
    f->acc_x_max   = af.col_max;
    f->acc_x_rms   = af.rms;
    f->acc_x_range = af.range;

    // acc_y
    af = compute_axis(ay, WINDOW_SIZE);
    f->acc_y_mean  = af.mean;
    f->acc_y_std   = af.std;
    f->acc_y_min   = af.col_min;
    f->acc_y_max   = af.col_max;
    f->acc_y_rms   = af.rms;
    f->acc_y_range = af.range;

    // acc_z
    af = compute_axis(az, WINDOW_SIZE);
    f->acc_z_mean  = af.mean;
    f->acc_z_std   = af.std;
    f->acc_z_min   = af.col_min;
    f->acc_z_max   = af.col_max;
    f->acc_z_rms   = af.rms;
    f->acc_z_range = af.range;

    // gyro_x
    af = compute_axis(gx, WINDOW_SIZE);
    f->gyro_x_mean  = af.mean;
    f->gyro_x_std   = af.std;
    f->gyro_x_min   = af.col_min;
    f->gyro_x_max   = af.col_max;
    f->gyro_x_rms   = af.rms;
    f->gyro_x_range = af.range;

    // gyro_y
    af = compute_axis(gy, WINDOW_SIZE);
    f->gyro_y_mean  = af.mean;
    f->gyro_y_std   = af.std;
    f->gyro_y_min   = af.col_min;
    f->gyro_y_max   = af.col_max;
    f->gyro_y_rms   = af.rms;
    f->gyro_y_range = af.range;

    // gyro_z
    af = compute_axis(gz, WINDOW_SIZE);
    f->gyro_z_mean  = af.mean;
    f->gyro_z_std   = af.std;
    f->gyro_z_min   = af.col_min;
    f->gyro_z_max   = af.col_max;
    f->gyro_z_rms   = af.rms;
    f->gyro_z_range = af.range;

    // ── SVM — Accelerometer ───────────────────────────────────────────────
    // Python: svm_acc = np.sqrt(window[:,0]**2 + window[:,1]**2 + window[:,2]**2)
    feat_svm(ax, ay, az, WINDOW_SIZE, &f->svm_acc_mean, &f->svm_acc_max);

    // ── SVM — Gyroscope ───────────────────────────────────────────────────
    // Python: svm_gyro = np.sqrt(window[:,3]**2 + window[:,4]**2 + window[:,5]**2)
    feat_svm(gx, gy, gz, WINDOW_SIZE, &f->svm_gyro_mean, &f->svm_gyro_max);

    // ── Jerk — Accelerometer axes only ────────────────────────────────────
    // Python loops: for i, ax in enumerate(["acc_x", "acc_y", "acc_z"])
    //   jerk = np.abs(np.diff(window[:, i]))
    //   feats[f"{ax}_jerk_mean"] = np.mean(jerk)
    //   feats[f"{ax}_jerk_var"]  = np.var(jerk)
    feat_jerk(ax, &f->acc_x_jerk_mean, &f->acc_x_jerk_var);
    feat_jerk(ay, &f->acc_y_jerk_mean, &f->acc_y_jerk_var);
    feat_jerk(az, &f->acc_z_jerk_mean, &f->acc_z_jerk_var);
}


// ============================================================
//  USAGE EXAMPLE (in your .ino sketch):
//
//  #include "features.h"
//  #include "fall_model.h"
//
//  float ax[WINDOW_SIZE], ay[WINDOW_SIZE], az[WINDOW_SIZE];
//  float gx[WINDOW_SIZE], gy[WINDOW_SIZE], gz[WINDOW_SIZE];
//
//  // ... fill arrays from MPU6050 circular buffer ...
//
//  Features f;
//  compute_features(ax, ay, az, gx, gy, gz, &f);
//
//  int probability = rf_fall_probability(&f);  // 0–100
//  int prediction  = rf_predict(&f);           // 0 or 1
// ============================================================
